//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Astro.Model.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Astro.Model.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verseau.
        /// </summary>
        internal static string SignAquariusName {
            get {
                return ResourceManager.GetString("SignAquariusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bélier.
        /// </summary>
        internal static string SignAriesName {
            get {
                return ResourceManager.GetString("SignAriesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancer.
        /// </summary>
        internal static string SignCancerName {
            get {
                return ResourceManager.GetString("SignCancerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capricorne.
        /// </summary>
        internal static string SignCapricornName {
            get {
                return ResourceManager.GetString("SignCapricornName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gémeaux.
        /// </summary>
        internal static string SignGeminiName {
            get {
                return ResourceManager.GetString("SignGeminiName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lion.
        /// </summary>
        internal static string SignLeoName {
            get {
                return ResourceManager.GetString("SignLeoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        internal static string SignLibraName {
            get {
                return ResourceManager.GetString("SignLibraName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poissons.
        /// </summary>
        internal static string SignPiscesName {
            get {
                return ResourceManager.GetString("SignPiscesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sagittaire.
        /// </summary>
        internal static string SignSagittariusName {
            get {
                return ResourceManager.GetString("SignSagittariusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scorpion.
        /// </summary>
        internal static string SignScorpioName {
            get {
                return ResourceManager.GetString("SignScorpioName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taureau.
        /// </summary>
        internal static string SignTaurusName {
            get {
                return ResourceManager.GetString("SignTaurusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vierge.
        /// </summary>
        internal static string SignVirgoName {
            get {
                return ResourceManager.GetString("SignVirgoName", resourceCulture);
            }
        }
    }
}
